name: PR size check
on:
  pull_request:
    types:
    - opened
    - edited
    - synchronized
    - labeled
    - unlabeled
jobs:
  check_pr_size:
    runs-on: ubuntu-latest
    steps:
    - uses: kkohtaka/gh-actions-pr-size@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
